CREATE DATABASE DrPhischel;
GO

USE DrPhischel;
GO

CREATE TABLE ROL (
	IdRol TINYINT INTEGRITY (1,1),
	Descripcion CHAR(15),

  CONSTRAINT PK_ROL
		PRIMARY KEY (IdRol),

	CONSTRAINT UK_ROL_Descripcion
		UNIQUE (Descripcion)
)


CREATE TABLE USER (
	Id INT IDENTITY(1,1),
	Password Char (20),

	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (Id),

	CONSTRAINT UK_CEDULA_CLIENTE
		UNIQUE(Cedula)
)

/* type of users */
CREATE TABLE PACIENTE (
	IdPaciente INT IDENTITY(1,1),
	Cedula CHAR(11),
	Nombre CHAR (15),
	Apellido CHAR(15),
	FechaNacimiento DATE,
	Residencia CHAR(45),
	Estado CHAR,
	Peso DECIMAL(3,2), /* kg */
	Altura DECIMAL(3), /* cm */

	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (IdPaciente),

	CONSTRAINT UK_CEDULA_CLIENTE
		UNIQUE(Cedula)
	)


CREATE TABLE DOCTOR(
	NoDoctor INT IDENTITY(1,1),
	Cedula CHAR(11),
	Nombre CHAR (15),
	Apellido CHAR(15),
	FechaNacimiento DATE,
	Residencia CHAR(45),
	Estado CHAR,
	DireccionConsultorio CHAR(50),
	Especialidad CHAR,
	TarjetaCredito DECIMAL(16),

	CONSTRAINT PK_DOCTOR
		PRIMARY KEY (NoDoctor),

	CONSTRAINT UK_DOCTOR_Cedula
		UNIQUE (Cedula)
	)


CREATE TABLE ADMINISTRADOR (
	IdAdmin INT IDENTITY(1,1),
	Cedula CHAR(11),
	Nombre CHAR (15),
	Apellido CHAR(15),
	FechaNacimiento DATE,
	Residencia CHAR(45),
	Estado CHAR,
	Hired DATE,

	CONSTRAINT PK_ADMINSTRADOR
		PRIMARY KEY (IdAdmin)
)

/* work related entities */
CREATE TABLE HISTORIAL (
	NoHistorial INT IDENTITY(1,1),
	Descripcion VARCHAR(30),
	Estudios VARCHAR(30),

	CONSTRAINT PK_HISTORIAL
		PRIMARY KEY (NoHistorial),
	)


CREATE TABLE RECETA(
	NoReceta INT IDENTITY(1,1),
	Imagen IMAGE,
	Estado CHAR,

	CONSTRAINT PK_RECETA
		PRIMARY KEY (NoReceta)
	)

	CREATE TABLE CITA (
		NoCita INT IDENTITY(1,1)
		Fecha DATE,
		Estado CHAR,

		CONSTRAINT PK_CITA
			PRIMARY KEY (NoCita)
	)


/* relationships */
CREATE TABLE ROL_POR_USUARIO (
	IdRol TINYINT,
	IdUsuario INT,

	CONSTRAINT PK_ROL_POR_USUARIO
		PRIMARY KEY (IdRol, IdUsuario),

	CONSTRAINT FK_PACIENTE_POR_DOCTOR_IdRol
		FOREIGN KEY(IdRol) REFERENCES ROL(Id),

	CONSTRAINT FK_PACIENTE_POR_DOCTOR_IdUsuario
		FOREIGN KEY(IdUsuario) REFERENCES USUARIO(Id)
)


CREATE TABLE PACIENTE_POR_DOCTOR (
	IdPaciente INT,
	NoDoctor INT,

	CONSTRAINT PK_PACIENTE_POR_DOCTOR
		PRIMARY KEY (IdPaciente, NoDoctor),

	CONSTRAINT FK_PACIENTE_POR_DOCTOR_IdPaciente
		FOREIGN KEY(IdPaciente) REFERENCES Paciente(IdPaciente),

	CONSTRAINT FK_PACIENTE_POR_DOCTOR_NoDoctor
		FOREIGN KEY(NoDoctor) REFERENCES Doctor(NoDoctor)
		)


	CREATE TABLE HISTORIAL_POR_PACIENTE (
		IdPaciente INT,
		NoHistorial INT,

		CONSTRAINT PK_HISTORIAL_POR_PACIENTE
			PRIMARY KEY (IdPaciente, NoHistorial),

		CONSTRAINT PK_HISTORIAL_POR_PACIENTE_IdPaciente
			FOREIGN KEY (IdPaciente) REFERENCES PACIENTE(IdPaciente),

		CONSTRAINT PK_HISTORIAL_POR_PACIENTE_NoHistorial
			FOREIGN KEY (NoHistorial) REFERENCES HISTORIAL(NoHistorial)
			)


CREATE TABLE RECETA_POR_HISTORIAL (
	NoHistorial INT,
	NoReceta INT,

	CONSTRAINT PK_RECETA_POR_HISTORIAL
		PRIMARY KEY (NoHistorial, NoReceta),

	CONSTRAINT FK_RECETA_POR_HISTORIAL_NoHistorial
		FOREIGN KEY (NoHistorial) REFERENCES HISTORIAL(NoHistorial),

	CONSTRAINT FK_RECETA_POR_HISTORIAL_NoReceta
		FOREIGN KEY (NoReceta) REFERENCES RECETA(NoReceta)
	)


CREATE TABLE DOCTOR_EMITE_RECETA (
	NoDoctor INT,
	NoReceta INT,

	CONSTRAINT PK_RECETA_PACIENTE_DOCTOR
		PRIMARY KEY (NoDoctor, NoReceta),

	CONSTRAINT FK_RECETA_PACIENTE_DOCTOR_NoDoctor
		FOREIGN KEY (NoDoctor) REFERENCES DOCTOR(NoDoctor),

	CONSTRAINT FK_RECETA_PACIENTE_DOCTOR_NoReceta
		FOREIGN KEY (NoReceta) REFERENCES RECETA(NoReceta)
		)

/* ternary relationship */
	CREATE TABLE PACIENTE_CITA_DOCTOR (
		IdPaciente INT,
		NoCita INT,
		NoDoctor INT,

		CONSTRAINT PK_CITA_PACIENTE_DOCTOR
			PRIMARY KEY (NoCita, IdPaciente, NoDoctor),

		CONSTRAINT FK_CITA_PACIENTE_DOCTOR_IdPaciente
			FOREIGN KEY (IdPaciente) REFERENCES PACIENTE(IdPaciente),

			CONSTRAINT FK_CITA_PACIENTE_DOCTOR_NoCita
				FOREIGN KEY (NoCita) REFERENCES CITA(NoCita),

		CONSTRAINT FK_CITA_PACIENTE_DOCTOR_NoDoctor
			FOREIGN KEY (NoDoctor) REFERENCES DOCTOR(NoDoctor)
	)

/*
CREATE TABLE USUARIO_PACIENTE?
CREATE TABLE USUARIO_DOCTOR?
CREATE TABLE USUARIO_ADMINISTRADOR?
*/
