SELECT * FROM ROL;
SELECT * FROM USUARIO;

SELECT * FROM ROL_POR_USUARIO

SELECT * FROM PACIENTE;
SELECT * FROM DOCTOR;
SELECT * FROM ADMINISTRADOR;

SELECT * FROM CITA;
SELECT * FROM CITA_POR_DOCTOR;
SELECT * FROM CITA_POR_PACIENTE;

SELECT * FROM RECETA;
SELECT * FROM RECETA_POR_HISTORIAL;
SELECT * FROM RECETA_POR_DOCTOR;

SELECT * FROM HISTORIALMEDICO;
SELECT * FROM HISTORIAL_POR_PACIENTE;

Select * from ESPECIALIDADMEDICA;

Select * from PACIENTE_POR_DOCTOR ;


